
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Toolkit;

/**
 * @author Dasun T. Bamunuarachchi
 */
public class ConfigureRTC extends javax.swing.JFrame {
    
    static ClipboardUpdater clipboardUpdater;
    static Thread updaterthread;
    static ConfigureRTC uiInstance;
    
            
    static void setClipboard(ClipboardUpdater clipboardUpdater) {
        ConfigureRTC.clipboardUpdater = clipboardUpdater;
    }
    
    /**
     * Creates new form ConfigureRTC
     */
    public ConfigureRTC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jCheckBoxT1Enable = new javax.swing.JCheckBox();
        jCheckBoxT2Enable = new javax.swing.JCheckBox();
        jCheckBoxRoman2Pali = new javax.swing.JCheckBox();
        jToggleBtnRestoreLast = new javax.swing.JToggleButton();
        jButtonEndService = new javax.swing.JButton();
        jButtonStartService = new javax.swing.JButton();
        jLabelStatusOfUpdater = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RT Unicode Converter App");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jCheckBoxT1Enable.setText("Unicode Conveter T1");
        jCheckBoxT1Enable.setEnabled(false);
        jCheckBoxT1Enable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxT1EnableActionPerformed(evt);
            }
        });

        jCheckBoxT2Enable.setSelected(true);
        jCheckBoxT2Enable.setText("Unicode Conveter T2");
        jCheckBoxT2Enable.setEnabled(false);

        jCheckBoxRoman2Pali.setText("Roman Pali Conveter");
        jCheckBoxRoman2Pali.setEnabled(false);

        jToggleBtnRestoreLast.setSelected(true);
        jToggleBtnRestoreLast.setText("Restore Last Text");
        jToggleBtnRestoreLast.setToolTipText("Restores the last text when ending the service(enable by default)");
        jToggleBtnRestoreLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleBtnRestoreLastActionPerformed(evt);
            }
        });

        jButtonEndService.setText("End Service");
        jButtonEndService.setToolTipText("End converting the text automatically");
        jButtonEndService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEndServiceActionPerformed(evt);
            }
        });

        jButtonStartService.setText("Start Service");
        jButtonStartService.setToolTipText("Start converting text in clipboard");
        jButtonStartService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartServiceActionPerformed(evt);
            }
        });

        jLabelStatusOfUpdater.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStatusOfUpdater.setText("...");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jCheckBoxT2Enable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jCheckBoxT1Enable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxRoman2Pali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelStatusOfUpdater, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(155, 155, 155))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButtonStartService)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEndService))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jToggleBtnRestoreLast)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxT1Enable)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxT2Enable)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxRoman2Pali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jToggleBtnRestoreLast)
                .addGap(18, 18, 18)
                .addComponent(jLabelStatusOfUpdater)
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEndService)
                    .addComponent(jButtonStartService))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxT1EnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxT1EnableActionPerformed
        
    }//GEN-LAST:event_jCheckBoxT1EnableActionPerformed

    private void jButtonStartServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartServiceActionPerformed
        clipboardUpdater.startThread();
        jLabelStatusOfUpdater.setText("Running");
        
    }//GEN-LAST:event_jButtonStartServiceActionPerformed

    private void jButtonEndServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEndServiceActionPerformed
        clipboardUpdater.stopThread();
        jLabelStatusOfUpdater.setText("Stopped");
        
    }//GEN-LAST:event_jButtonEndServiceActionPerformed

    private void jToggleBtnRestoreLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleBtnRestoreLastActionPerformed
       if(jToggleBtnRestoreLast.isSelected()){
           clipboardUpdater.setEnableRestoreLastText(true);
       }else{
           clipboardUpdater.setEnableRestoreLastText(false);
       }
    }//GEN-LAST:event_jToggleBtnRestoreLastActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(ConfigureRTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(ConfigureRTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(ConfigureRTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(ConfigureRTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(() -> {
                uiInstance = new ConfigureRTC();
                Rectangle rtangle = uiInstance.getBounds();

                Toolkit tk = Toolkit.getDefaultToolkit();
                Dimension dm = tk.getScreenSize();
                int vertical = -rtangle.height/2+dm.height/2;
                int horizontal = -rtangle.width/2+dm.width/2;
                uiInstance.setLocation(new Point(horizontal,vertical));
                uiInstance.setVisible(true);
                uiInstance.setResizable(false);
                clipboardUpdater = new ClipboardUpdater();
                updaterthread = new Thread(clipboardUpdater);
                updaterthread.start();
            });
        } catch (Throwable ex) {
            ex.printStackTrace();
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEndService;
    private javax.swing.JButton jButtonStartService;
    private javax.swing.JCheckBox jCheckBoxRoman2Pali;
    private javax.swing.JCheckBox jCheckBoxT1Enable;
    private javax.swing.JCheckBox jCheckBoxT2Enable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelStatusOfUpdater;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToggleButton jToggleBtnRestoreLast;
    // End of variables declaration//GEN-END:variables
}
